version: '3.7'

services:
  postgres:
    image: postgres
    container_name: car_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres:latest
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: car
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - car
  pgadmin:
    image: dpage/pgadmin4
    container_name: car_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: rdezhhoot@gmail.com
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - car
    restart: unless-stopped
    depends_on:
      - postgres
  redis:
    image: redis
    container_name: car_redis
    command: ["redis-server",'/etc/redis/redis.conf']
    volumes:
      - './redis/redis.conf:/etc/redis/redis.conf'
      - redis:/etc/redis.conf
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - car
volumes:
  postgres:
  pgadmin:
  redis:
  logs:

networks:
  car:
    driver: bridge